### ISSUE TITLE
Secutiry error #2048

### ISSUE THREAD

**Issue by TNTworks** [trapped/rotmg_svr#4]
Hello, im getting security error 2048 when joining nexus, last time it worked was using KrazyServer 0.5 using ur files, after that tried all versions of server without krazyserver tool, i got server working on ubuntu server using mono 2.10

No idea what causes that error

**Comment by trapped** [comment]
Error #2048: host unreachable. Check the IPs.

**Comment by TNTworks** [comment]
it was security error, but thanks going to check

**Comment by TNTworks** [comment]
srv:192.168.52.129
db:Server=localhost;Database=rotmg;uid=rotmg;password=

is in config, 192.168.52.129 is ip of Ubuntu Server on Virtual Machine, i can access outside VM, database is hosted on ubuntu server, on VM, localhost.swf have the strings, 3700 one, and 4200 one changed to 192.168.52.129 and 192.168.52.129:8080, when i start server.exe is says 8080, not 8888

If you need more info i will post it, also ubuntu server is english, no errors on both server and wserver

**Comment by trapped** [comment]
8080 is right.
I know it was /security/ error, it's the same.
Anyways, check the server>char>list.cs file for the DNS variable in the List<ServerItem> Servers thing: if it's different from db.confreader etc. then it's wrong, change it.
In the client there has to be the server.exe IP.

**Comment by TNTworks** [comment]
oh damn
didnt notice its not added

Long = 114.16,
                            DNS = "127.0.0.1",//db.confreader.getservers(false).ToString(), //127.0.0.1, CHANGE THIS TO LET YOUR FRIENDS CONNECT
                            Usage = 0.2,

gonna change it now

**Comment by trapped** [comment]
Problem solved, issue closed.

**Comment by TNTworks** [comment]
EDIT
Now its saying.
Conneting to local
Connected!
Connection Failed.Retriying

**Comment by trapped** [comment]
Did you make an account ingame?
