### ISSUE TITLE
Can't enter in Land's

### ISSUE THREAD

**Issue by carlosmuller** [trapped/rotmg_svr#5]
I can't enter in the lands like Medusa, catch the server  today(21/6/13) and can't enter the realms.
And you're a genius for doing that much work in this! And now a i realize that neither in the vault a cannot enter.
Thanks in advance

**Comment by trapped** [comment]
I fixed that already. Download the latest commit. You probably downloaded the commit I linked on MPGH, that's older.

**Comment by carlosmuller** [comment]
Sorry my bad did not rebuild the project !
