### ISSUE TITLE
Loading Error, Retrying

### ISSUE THREAD

**Issue by pjohn375** [trapped/rotmg_svr#6]
Hi, I recently saw JayDeeGamer's video montage of your project, and I was wondering if I could join in on the fun. So far i've downloaded the zip file, "rotmg_server_master." However when I open the client- it comes up with "Load error, retrying" I was wondering if you could help me out and tell me what I need to do to get the client working did so I can enjoy the game like it was in JayDeeGamer's video.

Please reply soon,
Thanks :D

**Comment by trapped** [comment]
JayDeeGamer is also known as Shadomir, the co-founder of the MMOEmpire organization (mmoe.net). The footage you saw was of their (althought I contribute in coding their server too) private (pay2join - they've got more features'n'stuff) server. This GitHub repo instead contains my personal public version of the code, open source and available for free, it requires some preparations to be used thought.
On MPGH (mpgh.net, RotMG section) there are tons of tutorials and other stuff regarding this software. There you can find a tutorial about how to set up your own server and how to play on it.
Have fun!
